/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'boost.browser-logs': [];
    'sanctum.csrf-cookie': [];
    index: [];
    'contact-us': [];
    'about-us': [];
    search: [];
    chatbot: [];
    'happy-family': [];
    'clean-life': [];
    'hn.index': [];
    'hn.start': [];
    'consultations.index': [];
    'consultations.in-person': [];
    'news.index': [];
    'news.show': [
      {
        name: 'news';
        required: true;
        binding: 'id';
      },
    ];
    'gardens.index': [];
    'gardens.show': [
      {
        name: 'garden';
        required: true;
        binding: 'id';
      },
    ];
    'series.index': [];
    'series.show': [
      {
        name: 'series';
        required: true;
        binding: 'id';
      },
    ];
    'series.episodes.index': [
      {
        name: 'series';
        required: true;
        binding: 'id';
      },
    ];
    'series.episodes.show': [
      {
        name: 'series';
        required: true;
        binding: 'id';
      },
      {
        name: 'episode';
        required: true;
      },
    ];
    'reward-programs.index': [];
    'reward-programs.show': [
      {
        name: 'reward_program';
        required: true;
      },
    ];
    'event-programs.index': [];
    'event-programs.show': [
      {
        name: 'event_program';
        required: true;
      },
    ];
    'contests.index': [];
    'contests.show': [
      {
        name: 'contest';
        required: true;
        binding: 'id';
      },
    ];
    'games.index': [];
    'games.nardeban-shadi': [];
    'games.roll-the-dice': [];
    'target-groups.active': [];
    'faqs.store': [];
    'question-forms.show': [
      {
        name: 'question_form';
        required: true;
      },
    ];
    'question-forms.answers.store': [
      {
        name: 'question_form';
        required: true;
      },
    ];
    'contests.upload-image': [
      {
        name: 'contest';
        required: true;
        binding: 'id';
      },
    ];
    'contests.registrations.store': [
      {
        name: 'contest';
        required: true;
        binding: 'id';
      },
    ];
    'series.owns.store': [
      {
        name: 'series';
        required: true;
        binding: 'id';
      },
    ];
    'me.score.convert-to-coupon': [];
    'me.score.transfer-to-my-isfahan': [];
    dashboard: [];
    'dashboard.score': [];
    'dashboard.account': [];
    'dashboard.orders': [];
    'dashboard.series': [];
    'mellat.callback': [];
    register: [];
    login: [];
    auth: [];
    'sms.send': [];
    'sms.verify': [];
    logout: [];
    'storage.local': [
      {
        name: 'path';
        required: true;
      },
    ];
  }
}
export {};
