/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'sanctum.csrf-cookie': [];
    index: [];
    'contact-us': [];
    'about-us': [];
    search: [];
    chatbot: [];
    'mellat.callback': [];
    'news.index': [];
    'news.show': [
      {
        name: 'news';
        required: true;
        binding: 'id';
      },
    ];
    'gardens.index': [];
    'gardens.show': [
      {
        name: 'garden';
        required: true;
        binding: 'id';
      },
    ];
    'series.index': [];
    'series.show': [
      {
        name: 'series';
        required: true;
        binding: 'id';
      },
    ];
    'series.episodes.index': [
      {
        name: 'series';
        required: true;
        binding: 'id';
      },
    ];
    'series.episodes.show': [
      {
        name: 'series';
        required: true;
        binding: 'id';
      },
      {
        name: 'episode';
        required: true;
      },
    ];
    'reward-programs.index': [];
    'reward-programs.show': [
      {
        name: 'reward_program';
        required: true;
      },
    ];
    'event-programs.index': [];
    'event-programs.show': [
      {
        name: 'event_program';
        required: true;
      },
    ];
    'contests.index': [];
    'contests.show': [
      {
        name: 'contest';
        required: true;
        binding: 'id';
      },
    ];
    'games.index': [];
    'games.nardeban-shadi': [];
    'games.roll-the-dice': [];
    'faqs.store': [];
    'contests.registrations.store': [
      {
        name: 'contest';
        required: true;
        binding: 'id';
      },
    ];
    'series.owns.store': [
      {
        name: 'series';
        required: true;
        binding: 'id';
      },
    ];
    'me.score.convert-to-coupon': [];
    'me.score.transfer-to-my-isfahan': [];
    dashboard: [];
    'dashboard.score': [];
    'dashboard.account': [];
    'dashboard.orders': [];
    'dashboard.series': [];
    register: [];
    login: [];
    'auth.my-isfahan': [];
    auth: [];
    'sms.send': [];
    'sms.verify': [];
    'sms.register': [];
    logout: [];
    'storage.local': [
      {
        name: 'path';
        required: true;
      },
    ];
  }
}
export {};
