/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'sanctum.csrf-cookie': [];
    index: [];
    contactUs: [];
    aboutUs: [];
    search: [];
    'series.index': [];
    'series.create': [];
    'series.store': [];
    'series.show': [
      {
        name: 'series';
        required: true;
      },
    ];
    'series.edit': [
      {
        name: 'series';
        required: true;
      },
    ];
    'series.update': [
      {
        name: 'series';
        required: true;
      },
    ];
    'series.destroy': [
      {
        name: 'series';
        required: true;
      },
    ];
    'reward-programs.index': [];
    'reward-programs.show': [
      {
        name: 'reward_program';
        required: true;
      },
    ];
    'contests.index': [];
    'contests.show': [
      {
        name: 'contest';
        required: true;
      },
    ];
    'campaigns.index': [];
    'campaigns.show': [
      {
        name: 'campaign';
        required: true;
      },
    ];
    'event-programs.index': [];
    'event-programs.show': [
      {
        name: 'event_program';
        required: true;
      },
    ];
    register: [];
    login: [];
    'password.request': [];
    'password.email': [];
    'password.reset': [
      {
        name: 'token';
        required: true;
      },
    ];
    'password.store': [];
    'verification.notice': [];
    'verification.verify': [
      {
        name: 'id';
        required: true;
      },
      {
        name: 'hash';
        required: true;
      },
    ];
    'verification.send': [];
    'password.confirm': [];
    'password.update': [];
    logout: [];
    'storage.local': [
      {
        name: 'path';
        required: true;
      },
    ];
  }
}
export {};
