<?php

namespace App\Filament\Pages;

use App\Filament\Forms\Layouts\BasicForm;
use App\Settings\ScoreSettings;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Pages\SettingsPage;
use Filament\Support\RawJs;

class ManageScore extends SettingsPage
{
    protected static ?string $navigationIcon = 'heroicon-o-cog-6-tooth';

    protected static string $settings = ScoreSettings::class;

    public function getTitle(): string
    {
        return __('Manage score');
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $data['score_to_coupon_logic'] = collect($data['score_to_coupon_logic'])
            ->sortByDesc(fn ($item) => $item['score_amount'])
            ->values()
            ->toArray();

        return $data;
    }

    public function afterSave(): void
    {
        $this->fillForm();
    }

    public static function getNavigationGroup(): ?string
    {
        return __('Settings');
    }

    public static function getNavigationLabel(): string
    {
        return __('Manage score'); // TODO: Change the autogenerated stub
    }

    public function form(Form $form): Form
    {
        return BasicForm::make($form, [
            Forms\Components\Repeater::make('score_to_coupon_logic')
                ->label('تبدیل امتیاز به کد تخفیف')
                ->required()
                ->reorderable(false)
                ->columnSpanFull()
                ->columns(2)
                ->schema([
                    Forms\Components\TextInput::make('score_amount')
                        ->translateLabel()
                        ->integer()
                        ->minValue(0)
                        ->stripCharacters(',')
                        ->mask(RawJs::make('$money($input)'))
                        ->required(),
                    Forms\Components\TextInput::make('coupon_amount')
                        ->translateLabel()
                        ->integer()
                        ->minValue(0)
                        ->suffix('تومان')
                        ->mask(RawJs::make('$money($input)'))
                        ->stripCharacters(',')
                        ->required(),
                ]),
        ]);
    }
}
